/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empleadoId 
 * @param ventas 
 * @param totalVendido 
 */


data class ActividadResponse (

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("ventas")
    val ventas: kotlin.Long? = null,

    @SerializedName("totalVendido")
    val totalVendido: java.math.BigDecimal? = null

) {


}

