/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SeleccionSlotDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param tipo 
 * @param empresaId 
 * @param clienteId 
 * @param prendaId 
 * @param disfrazId 
 * @param selecciones 
 * @param cantidad 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 */


data class AgregarItemRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("tipo")
    val tipo: AgregarItemRequest.Tipo,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("disfrazId")
    val disfrazId: java.util.UUID? = null,

    @SerializedName("selecciones")
    val selecciones: kotlin.collections.List<SeleccionSlotDto>? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class Tipo(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

