/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param estado 
 * @param delta 
 * @param motivo 
 */


data class AjusteDeStockRequest (

    @SerializedName("estado")
    val estado: AjusteDeStockRequest.Estado,

    @SerializedName("delta")
    val delta: kotlin.Int? = null,

    @SerializedName("motivo")
    val motivo: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: DISPONIBLE,RENTADA,DANADA,EN_LIMPIEZA,PERDIDA
     */
    enum class Estado(val value: kotlin.String) {
        @SerializedName(value = "DISPONIBLE") DISPONIBLE("DISPONIBLE"),
        @SerializedName(value = "RENTADA") RENTADA("RENTADA"),
        @SerializedName(value = "DANADA") DANADA("DANADA"),
        @SerializedName(value = "EN_LIMPIEZA") EN_LIMPIEZA("EN_LIMPIEZA"),
        @SerializedName(value = "PERDIDA") PERDIDA("PERDIDA");
    }

}

