/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rol 
 * @param email 
 * @param password 
 */


data class AltaDeEmpleadoRequest (

    @SerializedName("rol")
    val rol: AltaDeEmpleadoRequest.Rol,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("password")
    val password: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: SUPERADMIN,DUENO,ENCARGADO,MOSTRADOR,BODEGA,ATENCION,CLIENTE
     */
    enum class Rol(val value: kotlin.String) {
        @SerializedName(value = "SUPERADMIN") SUPERADMIN("SUPERADMIN"),
        @SerializedName(value = "DUENO") DUENO("DUENO"),
        @SerializedName(value = "ENCARGADO") ENCARGADO("ENCARGADO"),
        @SerializedName(value = "MOSTRADOR") MOSTRADOR("MOSTRADOR"),
        @SerializedName(value = "BODEGA") BODEGA("BODEGA"),
        @SerializedName(value = "ATENCION") ATENCION("ATENCION"),
        @SerializedName(value = "CLIENTE") CLIENTE("CLIENTE");
    }

}

