/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param nombre 
 * @param unidades 
 * @param monto 
 */


data class ArticuloRanking (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("unidades")
    val unidades: kotlin.Long? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null

) {


}

