/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param nombre 
 * @param fotoUrl 
 * @param unidades 
 * @param monto 
 */


data class ArticuloRanking (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("unidades")
    val unidades: kotlin.Long? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null

) {


}

