/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param accion 
 * @param detalle 
 * @param fecha 
 */


data class AuditoriaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("accion")
    val accion: kotlin.String? = null,

    @SerializedName("detalle")
    val detalle: kotlin.String? = null,

    @SerializedName("fecha")
    val fecha: java.time.OffsetDateTime? = null

) {


}

