/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contrasenaActual 
 * @param contrasenaNueva 
 */


data class CambiarContrasenaRequest (

    @SerializedName("contrasenaActual")
    val contrasenaActual: kotlin.String? = null,

    @SerializedName("contrasenaNueva")
    val contrasenaNueva: kotlin.String? = null

) {


}

