/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param modo 
 */


data class CambiarContextoRequest (

    @SerializedName("modo")
    val modo: CambiarContextoRequest.Modo

) {

    /**
     * 
     *
     * Values: COMPRA,TRABAJO
     */
    enum class Modo(val value: kotlin.String) {
        @SerializedName(value = "COMPRA") COMPRA("COMPRA"),
        @SerializedName(value = "TRABAJO") TRABAJO("TRABAJO");
    }

}

