/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param seccion 
 * @param capacidad 
 * @param descripcion 
 * @param concedido 
 */


data class CapacidadDto (

    @SerializedName("seccion")
    val seccion: kotlin.String? = null,

    @SerializedName("capacidad")
    val capacidad: kotlin.String? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("concedido")
    val concedido: kotlin.Boolean? = null

) {


}

