/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaDeCarritoResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param sucursalId 
 * @param clienteId 
 * @param tipo 
 * @param estado 
 * @param lineas 
 * @param total 
 */


data class CarritoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaDeCarritoResponse>? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null

) {


}

