/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empresaId 
 * @param empresaNombre 
 * @param sucursalId 
 * @param sucursalNombre 
 * @param tipo 
 * @param articulos 
 */


data class CarritoAbiertoResponse (

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("empresaNombre")
    val empresaNombre: kotlin.String? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("sucursalNombre")
    val sucursalNombre: kotlin.String? = null,

    @SerializedName("tipo")
    val tipo: CarritoAbiertoResponse.Tipo? = null,

    @SerializedName("articulos")
    val articulos: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class Tipo(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

