/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param nombre 
 * @param archivada 
 */


data class CategoriaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("archivada")
    val archivada: kotlin.Boolean? = null

) {


}

