/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param nombre 
 * @param telefono 
 * @param email 
 * @param documento 
 * @param direccion 
 * @param enListaNegra 
 * @param archivada 
 * @param saldoPendiente 
 * @param multaTotal 
 * @param tieneRentaEnCurso 
 */


data class ClienteResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("telefono")
    val telefono: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("documento")
    val documento: kotlin.String? = null,

    @SerializedName("direccion")
    val direccion: kotlin.String? = null,

    @SerializedName("enListaNegra")
    val enListaNegra: kotlin.Boolean? = null,

    @SerializedName("archivada")
    val archivada: kotlin.Boolean? = null,

    @SerializedName("saldoPendiente")
    val saldoPendiente: java.math.BigDecimal? = null,

    @SerializedName("multaTotal")
    val multaTotal: java.math.BigDecimal? = null,

    @SerializedName("tieneRentaEnCurso")
    val tieneRentaEnCurso: kotlin.Boolean? = null

) {


}

