/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.PagoResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pagos 
 * @param total 
 * @param vuelto 
 */


data class CobroMixtoResponse (

    @SerializedName("pagos")
    val pagos: kotlin.collections.List<PagoResponse>? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null,

    @SerializedName("vuelto")
    val vuelto: java.math.BigDecimal? = null

) {


}

