/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.EstadoDeposito
import com.costumi.apiclient.models.PagoResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conceptoId 
 * @param pagos 
 * @param totalCobrado 
 * @param totalReembolsado 
 * @param saldoNeto 
 * @param multa 
 * @param deposito 
 * @param tasaImpuesto 
 * @param baseImponible 
 * @param impuesto 
 */


data class ComprobanteResponse (

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID? = null,

    @SerializedName("pagos")
    val pagos: kotlin.collections.List<PagoResponse>? = null,

    @SerializedName("totalCobrado")
    val totalCobrado: java.math.BigDecimal? = null,

    @SerializedName("totalReembolsado")
    val totalReembolsado: java.math.BigDecimal? = null,

    @SerializedName("saldoNeto")
    val saldoNeto: java.math.BigDecimal? = null,

    @SerializedName("multa")
    val multa: java.math.BigDecimal? = null,

    @SerializedName("deposito")
    val deposito: EstadoDeposito? = null,

    @SerializedName("tasaImpuesto")
    val tasaImpuesto: java.math.BigDecimal? = null,

    @SerializedName("baseImponible")
    val baseImponible: java.math.BigDecimal? = null,

    @SerializedName("impuesto")
    val impuesto: java.math.BigDecimal? = null

) {


}

