/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conteoStock 
 * @param multasActivo 
 * @param multiSucursal 
 * @param pagoEnLinea 
 * @param tasaImpuesto 
 * @param moneda 
 * @param recargoPorRetrasoPorDia 
 * @param modoRecargoRetraso 
 * @param reembolsosActivos 
 * @param ventanaReembolsoDias 
 */


data class ConfiguracionResponse (

    @SerializedName("conteoStock")
    val conteoStock: kotlin.Boolean? = null,

    @SerializedName("multasActivo")
    val multasActivo: kotlin.Boolean? = null,

    @SerializedName("multiSucursal")
    val multiSucursal: kotlin.Boolean? = null,

    @SerializedName("pagoEnLinea")
    val pagoEnLinea: kotlin.Boolean? = null,

    @SerializedName("tasaImpuesto")
    val tasaImpuesto: java.math.BigDecimal? = null,

    @SerializedName("moneda")
    val moneda: kotlin.String? = null,

    @SerializedName("recargoPorRetrasoPorDia")
    val recargoPorRetrasoPorDia: java.math.BigDecimal? = null,

    @SerializedName("modoRecargoRetraso")
    val modoRecargoRetraso: ConfiguracionResponse.ModoRecargoRetraso? = null,

    @SerializedName("reembolsosActivos")
    val reembolsosActivos: kotlin.Boolean? = null,

    @SerializedName("ventanaReembolsoDias")
    val ventanaReembolsoDias: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: ACUMULATIVA,FIJA
     */
    enum class ModoRecargoRetraso(val value: kotlin.String) {
        @SerializedName(value = "ACUMULATIVA") ACUMULATIVA("ACUMULATIVA"),
        @SerializedName(value = "FIJA") FIJA("FIJA");
    }

}

