/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param defineVariante 
 * @param seleccionablePorCliente 
 * @param categoriasQueAplica 
 */


data class CrearTipoEtiquetaRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("defineVariante")
    val defineVariante: kotlin.Boolean? = null,

    @SerializedName("seleccionablePorCliente")
    val seleccionablePorCliente: kotlin.Boolean? = null,

    @SerializedName("categoriasQueAplica")
    val categoriasQueAplica: kotlin.collections.List<java.util.UUID>? = null

) {


}

