/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaRentaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param clienteId 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param deposito 
 * @param claveIdempotencia 
 * @param lineas 
 * @param prendaId 
 * @param precioPorDia 
 */


data class CrearRentaRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("claveIdempotencia")
    val claveIdempotencia: kotlin.String? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaRentaDto>? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("precioPorDia")
    val precioPorDia: java.math.BigDecimal? = null

) {


}

