/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SlotDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param categoriaId 
 * @param precioRentaGeneral 
 * @param precioVentaGeneral 
 * @param tipo 
 * @param slots 
 */


data class CrearDisfrazRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("categoriaId")
    val categoriaId: java.util.UUID? = null,

    @SerializedName("precioRentaGeneral")
    val precioRentaGeneral: java.math.BigDecimal? = null,

    @SerializedName("precioVentaGeneral")
    val precioVentaGeneral: java.math.BigDecimal? = null,

    @SerializedName("tipo")
    val tipo: CrearDisfrazRequest.Tipo? = null,

    @SerializedName("slots")
    val slots: kotlin.collections.List<SlotDto>? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA,AMBOS
     */
    enum class Tipo(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA"),
        @SerializedName(value = "AMBOS") AMBOS("AMBOS");
    }

}

