/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SeleccionVarianteDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param combinacion 
 * @param cantidadInicial 
 */


data class CrearGrupoDeStockRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("combinacion")
    val combinacion: kotlin.collections.List<SeleccionVarianteDto>? = null,

    @SerializedName("cantidadInicial")
    val cantidadInicial: kotlin.Int? = null

) {


}

