/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.PiezaResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param rentaId 
 * @param deposito 
 * @param cargoPorDanos 
 * @param cargoPorRetraso 
 * @param remanente 
 * @param multa 
 * @param piezas 
 */


data class DevolucionResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("rentaId")
    val rentaId: java.util.UUID? = null,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("cargoPorDanos")
    val cargoPorDanos: java.math.BigDecimal? = null,

    @SerializedName("cargoPorRetraso")
    val cargoPorRetraso: java.math.BigDecimal? = null,

    @SerializedName("remanente")
    val remanente: java.math.BigDecimal? = null,

    @SerializedName("multa")
    val multa: java.math.BigDecimal? = null,

    @SerializedName("piezas")
    val piezas: kotlin.collections.List<PiezaResponse>? = null

) {


}

