/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaADevolver

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lineas 
 */


data class DevolverVentaRequest (

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaADevolver>? = null

) {


}

