/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.MultaSugeridaDto
import com.costumi.apiclient.models.SlotDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param nombre 
 * @param categoriaId 
 * @param categoria 
 * @param tipo 
 * @param activo 
 * @param precioRentaGeneral 
 * @param precioVentaGeneral 
 * @param precioRentaSugerido 
 * @param precioRentaSugeridoMax 
 * @param precioVentaSugerido 
 * @param precioVentaSugeridoMax 
 * @param multaSugerida 
 * @param fotoUrl 
 * @param slots 
 */


data class DisfrazResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("categoriaId")
    val categoriaId: java.util.UUID? = null,

    @SerializedName("categoria")
    val categoria: kotlin.String? = null,

    @SerializedName("tipo")
    val tipo: DisfrazResponse.Tipo? = null,

    @SerializedName("activo")
    val activo: kotlin.Boolean? = null,

    @SerializedName("precioRentaGeneral")
    val precioRentaGeneral: java.math.BigDecimal? = null,

    @SerializedName("precioVentaGeneral")
    val precioVentaGeneral: java.math.BigDecimal? = null,

    @SerializedName("precioRentaSugerido")
    val precioRentaSugerido: java.math.BigDecimal? = null,

    @SerializedName("precioRentaSugeridoMax")
    val precioRentaSugeridoMax: java.math.BigDecimal? = null,

    @SerializedName("precioVentaSugerido")
    val precioVentaSugerido: java.math.BigDecimal? = null,

    @SerializedName("precioVentaSugeridoMax")
    val precioVentaSugeridoMax: java.math.BigDecimal? = null,

    @SerializedName("multaSugerida")
    val multaSugerida: MultaSugeridaDto? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("slots")
    val slots: kotlin.collections.List<SlotDto>? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA,AMBOS
     */
    enum class Tipo(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA"),
        @SerializedName(value = "AMBOS") AMBOS("AMBOS");
    }

}

