/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param disfrazId 
 * @param empresaId 
 * @param empresaNombre 
 * @param nombre 
 * @param fotoUrl 
 * @param precioRenta 
 * @param precioVenta 
 */


data class DisfrazDestacadoResponse (

    @SerializedName("disfrazId")
    val disfrazId: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("empresaNombre")
    val empresaNombre: kotlin.String? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("precioRenta")
    val precioRenta: java.math.BigDecimal? = null,

    @SerializedName("precioVenta")
    val precioVenta: java.math.BigDecimal? = null

) {


}

