/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.DisfrazResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param disfraz 
 * @param disponible 
 */


data class DisfrazDetalleResponse (

    @SerializedName("disfraz")
    val disfraz: DisfrazResponse? = null,

    @SerializedName("disponible")
    val disponible: kotlin.Boolean? = null

) {


}

