/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param direccion 
 * @param ubicacionMaps 
 * @param descripcion 
 * @param latitud 
 * @param longitud 
 */


data class EditarSucursalRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("direccion")
    val direccion: kotlin.String? = null,

    @SerializedName("ubicacionMaps")
    val ubicacionMaps: kotlin.String? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("latitud")
    val latitud: kotlin.Double? = null,

    @SerializedName("longitud")
    val longitud: kotlin.Double? = null

) {


}

