/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param telefono 
 * @param documento 
 * @param direccion 
 */


data class EditarClienteRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("telefono")
    val telefono: kotlin.String? = null,

    @SerializedName("documento")
    val documento: kotlin.String? = null,

    @SerializedName("direccion")
    val direccion: kotlin.String? = null

) {


}

