/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param email 
 * @param rol 
 * @param activo 
 */


data class EmpleadoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("rol")
    val rol: kotlin.String? = null,

    @SerializedName("activo")
    val activo: kotlin.Boolean? = null

) {


}

