/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empleadoId 
 * @param email 
 * @param numeroVentas 
 * @param total 
 */


data class EmpleadoVentas (

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("numeroVentas")
    val numeroVentas: kotlin.Long? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null

) {


}

