/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param nombre 
 * @param estado 
 * @param fechaRegistro 
 * @param ubicacion 
 * @param contacto 
 */


data class EmpresaResumenResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fechaRegistro")
    val fechaRegistro: java.time.OffsetDateTime? = null,

    @SerializedName("ubicacion")
    val ubicacion: kotlin.String? = null,

    @SerializedName("contacto")
    val contacto: kotlin.String? = null

) {


}

