/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param nombre 
 * @param estado 
 * @param fechaRegistro 
 * @param descripcion 
 * @param ciudad 
 * @param ubicacion 
 * @param contacto 
 * @param logoUrl 
 * @param portadaUrl 
 */


data class EmpresaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fechaRegistro")
    val fechaRegistro: java.time.OffsetDateTime? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("ciudad")
    val ciudad: kotlin.String? = null,

    @SerializedName("ubicacion")
    val ubicacion: kotlin.String? = null,

    @SerializedName("contacto")
    val contacto: kotlin.String? = null,

    @SerializedName("logoUrl")
    val logoUrl: kotlin.String? = null,

    @SerializedName("portadaUrl")
    val portadaUrl: kotlin.String? = null

) {


}

