/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canal 
 * @param clienteId 
 * @param mensaje 
 */


data class EnviarNotificacionRequest (

    @SerializedName("canal")
    val canal: EnviarNotificacionRequest.Canal,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("mensaje")
    val mensaje: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: WHATSAPP,FCM,EMAIL,IN_APP
     */
    enum class Canal(val value: kotlin.String) {
        @SerializedName(value = "WHATSAPP") WHATSAPP("WHATSAPP"),
        @SerializedName(value = "FCM") FCM("FCM"),
        @SerializedName(value = "EMAIL") EMAIL("EMAIL"),
        @SerializedName(value = "IN_APP") IN_APP("IN_APP");
    }

}

