/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conceptoId 
 * @param retenido 
 * @param devuelto 
 * @param activo 
 */


data class EstadoDeposito (

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID? = null,

    @SerializedName("retenido")
    val retenido: java.math.BigDecimal? = null,

    @SerializedName("devuelto")
    val devuelto: java.math.BigDecimal? = null,

    @SerializedName("activo")
    val activo: java.math.BigDecimal? = null

) {


}

