/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fcmConfigurado 
 * @param fcmDetalle 
 * @param whatsAppConfigurado 
 */


data class EstadoDeCanales (

    @SerializedName("fcmConfigurado")
    val fcmConfigurado: kotlin.Boolean? = null,

    @SerializedName("fcmDetalle")
    val fcmDetalle: kotlin.String? = null,

    @SerializedName("whatsAppConfigurado")
    val whatsAppConfigurado: kotlin.Boolean? = null

) {


}

