/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaEstadoResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param clienteId 
 * @param saldoTotal 
 * @param multaTotal 
 * @param lineas 
 */


data class EstadoDeCuentaResponse (

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("saldoTotal")
    val saldoTotal: java.math.BigDecimal? = null,

    @SerializedName("multaTotal")
    val multaTotal: java.math.BigDecimal? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaEstadoResponse>? = null

) {


}

