/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoEtiquetaId 
 * @param valorEtiquetaId 
 */


data class EtiquetaSeleccionadaDto (

    @SerializedName("tipoEtiquetaId")
    val tipoEtiquetaId: java.util.UUID,

    @SerializedName("valorEtiquetaId")
    val valorEtiquetaId: java.util.UUID

) {


}

