/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoEtiquetaId 
 * @param valores 
 */


data class EtiquetaPermitidaDto (

    @SerializedName("tipoEtiquetaId")
    val tipoEtiquetaId: java.util.UUID,

    @SerializedName("valores")
    val valores: kotlin.collections.List<java.util.UUID>? = null

) {


}

