/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nuevaFechaDevolucion 
 */


data class ExtenderRentaRequest (

    @SerializedName("nuevaFechaDevolucion")
    val nuevaFechaDevolucion: java.time.LocalDate? = null

) {


}

