/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.ValorDeFacetaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoEtiquetaId 
 * @param tipoNombre 
 * @param valores 
 */


data class FacetaDto (

    @SerializedName("tipoEtiquetaId")
    val tipoEtiquetaId: java.util.UUID? = null,

    @SerializedName("tipoNombre")
    val tipoNombre: kotlin.String? = null,

    @SerializedName("valores")
    val valores: kotlin.collections.List<ValorDeFacetaDto>? = null

) {


}

