/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ingresos 
 * @param costoDeVentas 
 * @param ganancia 
 */


data class GananciaResponse (

    @SerializedName("ingresos")
    val ingresos: java.math.BigDecimal? = null,

    @SerializedName("costoDeVentas")
    val costoDeVentas: java.math.BigDecimal? = null,

    @SerializedName("ganancia")
    val ganancia: java.math.BigDecimal? = null

) {


}

