/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param prendaNombre 
 * @param disponibles 
 * @param rentadas 
 * @param danadas 
 * @param enLimpieza 
 * @param perdidas 
 */


data class GrupoInventario (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("prendaNombre")
    val prendaNombre: kotlin.String? = null,

    @SerializedName("disponibles")
    val disponibles: kotlin.Int? = null,

    @SerializedName("rentadas")
    val rentadas: kotlin.Int? = null,

    @SerializedName("danadas")
    val danadas: kotlin.Int? = null,

    @SerializedName("enLimpieza")
    val enLimpieza: kotlin.Int? = null,

    @SerializedName("perdidas")
    val perdidas: kotlin.Int? = null

) {


}

