/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SeleccionVarianteDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param sucursalId 
 * @param prendaId 
 * @param combinacion 
 * @param disponibles 
 * @param rentadas 
 * @param danadas 
 * @param enLimpieza 
 * @param perdidas 
 * @param total 
 */


data class GrupoDeStockResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("combinacion")
    val combinacion: kotlin.collections.List<SeleccionVarianteDto>? = null,

    @SerializedName("disponibles")
    val disponibles: kotlin.Int? = null,

    @SerializedName("rentadas")
    val rentadas: kotlin.Int? = null,

    @SerializedName("danadas")
    val danadas: kotlin.Int? = null,

    @SerializedName("enLimpieza")
    val enLimpieza: kotlin.Int? = null,

    @SerializedName("perdidas")
    val perdidas: kotlin.Int? = null,

    @SerializedName("total")
    val total: kotlin.Int? = null

) {


}

