/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaDeHistorial

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipo 
 * @param operacionId 
 * @param codigoRetiro 
 * @param monto 
 * @param estado 
 * @param fecha 
 * @param empresaId 
 * @param empresaNombre 
 * @param lineas 
 */


data class HistorialItem (

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("operacionId")
    val operacionId: java.util.UUID? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fecha")
    val fecha: java.time.LocalDate? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("empresaNombre")
    val empresaNombre: kotlin.String? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaDeHistorial>? = null

) {


}

