/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param efectivo 
 * @param tarjeta 
 * @param transferencia 
 * @param total 
 */


data class IngresosPorMetodo (

    @SerializedName("efectivo")
    val efectivo: java.math.BigDecimal? = null,

    @SerializedName("tarjeta")
    val tarjeta: java.math.BigDecimal? = null,

    @SerializedName("transferencia")
    val transferencia: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null

) {


}

