/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ingresosPorRenta 
 * @param ingresosPorVenta 
 * @param total 
 */


data class IngresosResponse (

    @SerializedName("ingresosPorRenta")
    val ingresosPorRenta: java.math.BigDecimal? = null,

    @SerializedName("ingresosPorVenta")
    val ingresosPorVenta: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null

) {


}

