/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param monto 
 * @param moneda 
 */


data class IntentoDePagoRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("tipoConcepto")
    val tipoConcepto: IntentoDePagoRequest.TipoConcepto,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("moneda")
    val moneda: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

