/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param intentoId 
 * @param urlCheckout 
 */


data class IntentoDePagoResponse (

    @SerializedName("intentoId")
    val intentoId: java.util.UUID? = null,

    @SerializedName("urlCheckout")
    val urlCheckout: kotlin.String? = null

) {


}

