/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param precioUnitario 
 * @param cantidad 
 */


data class LineaPrendaVentaDto (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID,

    @SerializedName("precioUnitario")
    val precioUnitario: java.math.BigDecimal,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null

) {


}

