/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param nombre 
 * @param fotoUrl 
 * @param cantidad 
 * @param precioPorDia 
 * @param disfrazId 
 * @param disfrazNombre 
 * @param disfrazGrupo 
 * @param disfrazCantidad 
 */


data class LineaRentaResponse (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null,

    @SerializedName("precioPorDia")
    val precioPorDia: java.math.BigDecimal? = null,

    @SerializedName("disfrazId")
    val disfrazId: java.util.UUID? = null,

    @SerializedName("disfrazNombre")
    val disfrazNombre: kotlin.String? = null,

    @SerializedName("disfrazGrupo")
    val disfrazGrupo: java.util.UUID? = null,

    @SerializedName("disfrazCantidad")
    val disfrazCantidad: kotlin.Int? = null

) {


}

