/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rentaId 
 * @param codigoRetiro 
 * @param estado 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param importe 
 * @param cargoPorDanos 
 * @param cargoPorRetraso 
 * @param deposito 
 * @param multa 
 * @param pagado 
 * @param saldo 
 */


data class LineaEstadoResponse (

    @SerializedName("rentaId")
    val rentaId: java.util.UUID? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null,

    @SerializedName("importe")
    val importe: java.math.BigDecimal? = null,

    @SerializedName("cargoPorDanos")
    val cargoPorDanos: java.math.BigDecimal? = null,

    @SerializedName("cargoPorRetraso")
    val cargoPorRetraso: java.math.BigDecimal? = null,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("multa")
    val multa: java.math.BigDecimal? = null,

    @SerializedName("pagado")
    val pagado: java.math.BigDecimal? = null,

    @SerializedName("saldo")
    val saldo: java.math.BigDecimal? = null

) {


}

