/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param precioPorDia 
 * @param cantidad 
 */


data class LineaPrendaRentaDto (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID,

    @SerializedName("precioPorDia")
    val precioPorDia: java.math.BigDecimal,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null

) {


}

