/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SeleccionResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param prendaId 
 * @param disfrazId 
 * @param nombre 
 * @param fotoUrl 
 * @param cantidad 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param precioUnitario 
 * @param subtotal 
 * @param motivoNoDisponible 
 * @param selecciones 
 */


data class LineaDeCarritoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("disfrazId")
    val disfrazId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null,

    @SerializedName("precioUnitario")
    val precioUnitario: java.math.BigDecimal? = null,

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @SerializedName("motivoNoDisponible")
    val motivoNoDisponible: kotlin.String? = null,

    @SerializedName("selecciones")
    val selecciones: kotlin.collections.List<SeleccionResponse>? = null

) {


}

