/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param desde 
 * @param hacia 
 * @param cantidad 
 */


data class MoverUnidadesRequest (

    @SerializedName("desde")
    val desde: MoverUnidadesRequest.Desde,

    @SerializedName("hacia")
    val hacia: MoverUnidadesRequest.Hacia,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: DISPONIBLE,RENTADA,DANADA,EN_LIMPIEZA,PERDIDA
     */
    enum class Desde(val value: kotlin.String) {
        @SerializedName(value = "DISPONIBLE") DISPONIBLE("DISPONIBLE"),
        @SerializedName(value = "RENTADA") RENTADA("RENTADA"),
        @SerializedName(value = "DANADA") DANADA("DANADA"),
        @SerializedName(value = "EN_LIMPIEZA") EN_LIMPIEZA("EN_LIMPIEZA"),
        @SerializedName(value = "PERDIDA") PERDIDA("PERDIDA");
    }
    /**
     * 
     *
     * Values: DISPONIBLE,RENTADA,DANADA,EN_LIMPIEZA,PERDIDA
     */
    enum class Hacia(val value: kotlin.String) {
        @SerializedName(value = "DISPONIBLE") DISPONIBLE("DISPONIBLE"),
        @SerializedName(value = "RENTADA") RENTADA("RENTADA"),
        @SerializedName(value = "DANADA") DANADA("DANADA"),
        @SerializedName(value = "EN_LIMPIEZA") EN_LIMPIEZA("EN_LIMPIEZA"),
        @SerializedName(value = "PERDIDA") PERDIDA("PERDIDA");
    }

}

