/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipo 
 * @param concepto 
 * @param monto 
 * @param metodo 
 */


data class MovimientoResponse (

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("concepto")
    val concepto: kotlin.String? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null,

    @SerializedName("metodo")
    val metodo: kotlin.String? = null

) {


}

