/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param danoMin 
 * @param danoMax 
 * @param reposicionMin 
 * @param reposicionMax 
 */


data class MultaSugeridaDto (

    @SerializedName("danoMin")
    val danoMin: java.math.BigDecimal? = null,

    @SerializedName("danoMax")
    val danoMax: java.math.BigDecimal? = null,

    @SerializedName("reposicionMin")
    val reposicionMin: java.math.BigDecimal? = null,

    @SerializedName("reposicionMax")
    val reposicionMax: java.math.BigDecimal? = null

) {


}

