/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param clienteId 
 * @param canal 
 * @param mensaje 
 * @param estado 
 * @param fecha 
 */


data class NotificacionResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("canal")
    val canal: kotlin.String? = null,

    @SerializedName("mensaje")
    val mensaje: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fecha")
    val fecha: java.time.OffsetDateTime? = null

) {


}

