/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param clienteId 
 * @param clienteNombre 
 * @param canal 
 * @param mensaje 
 * @param estado 
 * @param fecha 
 */


data class NotificacionResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("clienteNombre")
    val clienteNombre: kotlin.String? = null,

    @SerializedName("canal")
    val canal: kotlin.String? = null,

    @SerializedName("mensaje")
    val mensaje: kotlin.String? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("fecha")
    val fecha: java.time.OffsetDateTime? = null

) {


}

