/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.EtiquetaValorDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param nombre 
 * @param fotoUrl 
 * @param precioRenta 
 * @param unidadesDisponibles 
 * @param etiquetas 
 */


data class OpcionDto (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("precioRenta")
    val precioRenta: java.math.BigDecimal? = null,

    @SerializedName("unidadesDisponibles")
    val unidadesDisponibles: kotlin.Int? = null,

    @SerializedName("etiquetas")
    val etiquetas: kotlin.collections.List<EtiquetaValorDto>? = null

) {


}

