/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param sucursalId 
 * @param empleadoId 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param monto 
 * @param tipoPago 
 * @param metodo 
 * @param referencia 
 * @param fecha 
 * @param codigoRetiro 
 */


data class PagoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("tipoConcepto")
    val tipoConcepto: kotlin.String? = null,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null,

    @SerializedName("tipoPago")
    val tipoPago: kotlin.String? = null,

    @SerializedName("metodo")
    val metodo: kotlin.String? = null,

    @SerializedName("referencia")
    val referencia: kotlin.String? = null,

    @SerializedName("fecha")
    val fecha: java.time.OffsetDateTime? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null

) {


}

