/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param email 
 * @param nombre 
 * @param telefono 
 * @param nombreParaMostrar 
 * @param rol 
 * @param empresaId 
 */


data class PerfilResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("telefono")
    val telefono: kotlin.String? = null,

    @SerializedName("nombreParaMostrar")
    val nombreParaMostrar: kotlin.String? = null,

    @SerializedName("rol")
    val rol: kotlin.String? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null

) {


}

