/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param seccion 
 * @param accion 
 * @param concedido 
 */


data class PermisoDto (

    @SerializedName("seccion")
    val seccion: PermisoDto.Seccion? = null,

    @SerializedName("accion")
    val accion: PermisoDto.Accion? = null,

    @SerializedName("concedido")
    val concedido: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: INVENTARIO,DISFRACES,VENTAS,RENTAS,DEVOLUCIONES,PAGOS,CAJA,REPORTES,CLIENTES,CONFIGURACION,NOTIFICACIONES,EMPLEADOS
     */
    enum class Seccion(val value: kotlin.String) {
        @SerializedName(value = "INVENTARIO") INVENTARIO("INVENTARIO"),
        @SerializedName(value = "DISFRACES") DISFRACES("DISFRACES"),
        @SerializedName(value = "VENTAS") VENTAS("VENTAS"),
        @SerializedName(value = "RENTAS") RENTAS("RENTAS"),
        @SerializedName(value = "DEVOLUCIONES") DEVOLUCIONES("DEVOLUCIONES"),
        @SerializedName(value = "PAGOS") PAGOS("PAGOS"),
        @SerializedName(value = "CAJA") CAJA("CAJA"),
        @SerializedName(value = "REPORTES") REPORTES("REPORTES"),
        @SerializedName(value = "CLIENTES") CLIENTES("CLIENTES"),
        @SerializedName(value = "CONFIGURACION") CONFIGURACION("CONFIGURACION"),
        @SerializedName(value = "NOTIFICACIONES") NOTIFICACIONES("NOTIFICACIONES"),
        @SerializedName(value = "EMPLEADOS") EMPLEADOS("EMPLEADOS");
    }
    /**
     * 
     *
     * Values: VER,ACCION
     */
    enum class Accion(val value: kotlin.String) {
        @SerializedName(value = "VER") VER("VER"),
        @SerializedName(value = "ACCION") ACCION("ACCION");
    }

}

