/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param nombre 
 * @param fotoUrl 
 * @param descripcion 
 * @param llego 
 * @param estado 
 * @param perdidaCobrada 
 * @param resuelta 
 */


data class PiezaResponse (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("llego")
    val llego: kotlin.Boolean? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("perdidaCobrada")
    val perdidaCobrada: kotlin.Boolean? = null,

    @SerializedName("resuelta")
    val resuelta: kotlin.Boolean? = null

) {


}

