/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param prendaId 
 * @param estado 
 * @param descripcion 
 * @param llego 
 * @param perdidaCobrada 
 */


data class PiezaRequest (

    @SerializedName("prendaId")
    val prendaId: java.util.UUID,

    @SerializedName("estado")
    val estado: PiezaRequest.Estado,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("llego")
    val llego: kotlin.Boolean? = null,

    @SerializedName("perdidaCobrada")
    val perdidaCobrada: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: BIEN,DANADA,EN_LIMPIEZA,PERDIDA
     */
    enum class Estado(val value: kotlin.String) {
        @SerializedName(value = "BIEN") BIEN("BIEN"),
        @SerializedName(value = "DANADA") DANADA("DANADA"),
        @SerializedName(value = "EN_LIMPIEZA") EN_LIMPIEZA("EN_LIMPIEZA"),
        @SerializedName(value = "PERDIDA") PERDIDA("PERDIDA");
    }

}

