/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.EtiquetaPermitidaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param categoriaId 
 * @param etiquetasPermitidas 
 */


data class PoolDto (

    @SerializedName("categoriaId")
    val categoriaId: java.util.UUID,

    @SerializedName("etiquetasPermitidas")
    val etiquetasPermitidas: kotlin.collections.List<EtiquetaPermitidaDto>? = null

) {


}

