/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param metodo 
 * @param monto 
 * @param referencia 
 */


data class Porcion (

    @SerializedName("metodo")
    val metodo: Porcion.Metodo,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("referencia")
    val referencia: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: EFECTIVO,TARJETA,TRANSFERENCIA
     */
    enum class Metodo(val value: kotlin.String) {
        @SerializedName(value = "EFECTIVO") EFECTIVO("EFECTIVO"),
        @SerializedName(value = "TARJETA") TARJETA("TARJETA"),
        @SerializedName(value = "TRANSFERENCIA") TRANSFERENCIA("TRANSFERENCIA");
    }

}

