/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.EtiquetaSeleccionadaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param nombre 
 * @param categoriaId 
 * @param tipoArticulo 
 * @param precioRenta 
 * @param precioVenta 
 * @param valorDano 
 * @param valorReposicion 
 * @param fotoUrl 
 * @param unidadesDisponibles 
 * @param etiquetas 
 */


data class PrendaDeCatalogoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("categoriaId")
    val categoriaId: java.util.UUID? = null,

    @SerializedName("tipoArticulo")
    val tipoArticulo: kotlin.String? = null,

    @SerializedName("precioRenta")
    val precioRenta: java.math.BigDecimal? = null,

    @SerializedName("precioVenta")
    val precioVenta: java.math.BigDecimal? = null,

    @SerializedName("valorDano")
    val valorDano: java.math.BigDecimal? = null,

    @SerializedName("valorReposicion")
    val valorReposicion: java.math.BigDecimal? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("unidadesDisponibles")
    val unidadesDisponibles: kotlin.Int? = null,

    @SerializedName("etiquetas")
    val etiquetas: kotlin.collections.List<EtiquetaSeleccionadaDto>? = null

) {


}

