/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param nombre 
 * @param tipoArticulo 
 * @param precioRenta 
 * @param precioVenta 
 * @param categoria 
 * @param fotoUrl 
 */


data class PrendaVitrinaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("tipoArticulo")
    val tipoArticulo: kotlin.String? = null,

    @SerializedName("precioRenta")
    val precioRenta: java.math.BigDecimal? = null,

    @SerializedName("precioVenta")
    val precioVenta: java.math.BigDecimal? = null,

    @SerializedName("categoria")
    val categoria: kotlin.String? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null,

    @SerializedName("etiquetas")
    val etiquetas: kotlin.collections.List<EtiquetaVitrinaDto>? = null

) {


}

