/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.EtiquetaSeleccionadaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param categoriaId 
 * @param nombre 
 * @param tipoArticulo 
 * @param precioRenta 
 * @param precioVenta 
 * @param costoAdquisicion 
 * @param depositoSugerido 
 * @param valorReposicion 
 * @param valorDano 
 * @param etiquetas 
 * @param archivada 
 * @param fotoUrl 
 */


data class PrendaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("categoriaId")
    val categoriaId: java.util.UUID? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("tipoArticulo")
    val tipoArticulo: PrendaResponse.TipoArticulo? = null,

    @SerializedName("precioRenta")
    val precioRenta: java.math.BigDecimal? = null,

    @SerializedName("precioVenta")
    val precioVenta: java.math.BigDecimal? = null,

    @SerializedName("costoAdquisicion")
    val costoAdquisicion: java.math.BigDecimal? = null,

    @SerializedName("depositoSugerido")
    val depositoSugerido: java.math.BigDecimal? = null,

    @SerializedName("valorReposicion")
    val valorReposicion: java.math.BigDecimal? = null,

    @SerializedName("valorDano")
    val valorDano: java.math.BigDecimal? = null,

    @SerializedName("etiquetas")
    val etiquetas: kotlin.collections.List<EtiquetaSeleccionadaDto>? = null,

    @SerializedName("archivada")
    val archivada: kotlin.Boolean? = null,

    @SerializedName("fotoUrl")
    val fotoUrl: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA,AMBOS
     */
    enum class TipoArticulo(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA"),
        @SerializedName(value = "AMBOS") AMBOS("AMBOS");
    }

}

