/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * Detalle de un problema según RFC 7807.
 *
 * @param type URI que identifica el tipo de error.
 * @param title Resumen legible del tipo de error.
 * @param status Código de estado HTTP.
 * @param detail Explicación específica de esta ocurrencia.
 * @param instance URI del recurso afectado.
 */


data class ProblemDetail (

    /* URI que identifica el tipo de error. */
    @SerializedName("type")
    val type: java.net.URI? = null,

    /* Resumen legible del tipo de error. */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* Código de estado HTTP. */
    @SerializedName("status")
    val status: kotlin.Int? = null,

    /* Explicación específica de esta ocurrencia. */
    @SerializedName("detail")
    val detail: kotlin.String? = null,

    /* URI del recurso afectado. */
    @SerializedName("instance")
    val instance: java.net.URI? = null

) {


}

