/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.Porcion

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param porciones 
 * @param efectivoRecibido 
 * @param claveIdempotencia 
 */


data class RegistrarCobroMixtoRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("tipoConcepto")
    val tipoConcepto: RegistrarCobroMixtoRequest.TipoConcepto,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID,

    @SerializedName("porciones")
    val porciones: kotlin.collections.List<Porcion>? = null,

    @SerializedName("efectivoRecibido")
    val efectivoRecibido: java.math.BigDecimal? = null,

    @SerializedName("claveIdempotencia")
    val claveIdempotencia: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

