/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaVentaRequest

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param clienteId 
 * @param descuento 
 * @param claveIdempotencia 
 * @param lineas 
 */


data class RegistrarVentaRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("descuento")
    val descuento: java.math.BigDecimal? = null,

    @SerializedName("claveIdempotencia")
    val claveIdempotencia: kotlin.String? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaVentaRequest>? = null

) {


}

