/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param monto 
 * @param metodo 
 * @param tipoPago 
 * @param referencia 
 * @param claveIdempotencia 
 */


data class RegistrarPagoRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("tipoConcepto")
    val tipoConcepto: RegistrarPagoRequest.TipoConcepto,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("metodo")
    val metodo: RegistrarPagoRequest.Metodo,

    @SerializedName("tipoPago")
    val tipoPago: RegistrarPagoRequest.TipoPago? = null,

    @SerializedName("referencia")
    val referencia: kotlin.String? = null,

    @SerializedName("claveIdempotencia")
    val claveIdempotencia: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }
    /**
     * 
     *
     * Values: EFECTIVO,TARJETA,TRANSFERENCIA
     */
    enum class Metodo(val value: kotlin.String) {
        @SerializedName(value = "EFECTIVO") EFECTIVO("EFECTIVO"),
        @SerializedName(value = "TARJETA") TARJETA("TARJETA"),
        @SerializedName(value = "TRANSFERENCIA") TRANSFERENCIA("TRANSFERENCIA");
    }
    /**
     * 
     *
     * Values: COBRO,REEMBOLSO,DEPOSITO,DEVOLUCION_DEPOSITO
     */
    enum class TipoPago(val value: kotlin.String) {
        @SerializedName(value = "COBRO") COBRO("COBRO"),
        @SerializedName(value = "REEMBOLSO") REEMBOLSO("REEMBOLSO"),
        @SerializedName(value = "DEPOSITO") DEPOSITO("DEPOSITO"),
        @SerializedName(value = "DEVOLUCION_DEPOSITO") DEVOLUCION_DEPOSITO("DEVOLUCION_DEPOSITO");
    }

}

