/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipo 
 * @param monto 
 * @param metodo 
 * @param concepto 
 */


data class RegistrarMovimientoRequest (

    @SerializedName("tipo")
    val tipo: RegistrarMovimientoRequest.Tipo,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("metodo")
    val metodo: RegistrarMovimientoRequest.Metodo,

    @SerializedName("concepto")
    val concepto: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: INGRESO,EGRESO
     */
    enum class Tipo(val value: kotlin.String) {
        @SerializedName(value = "INGRESO") INGRESO("INGRESO"),
        @SerializedName(value = "EGRESO") EGRESO("EGRESO");
    }
    /**
     * 
     *
     * Values: EFECTIVO,TARJETA,TRANSFERENCIA
     */
    enum class Metodo(val value: kotlin.String) {
        @SerializedName(value = "EFECTIVO") EFECTIVO("EFECTIVO"),
        @SerializedName(value = "TARJETA") TARJETA("TARJETA"),
        @SerializedName(value = "TRANSFERENCIA") TRANSFERENCIA("TRANSFERENCIA");
    }

}

