/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param ubicacion 
 * @param contacto 
 */


data class RegistrarEmpresaRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("ubicacion")
    val ubicacion: kotlin.String? = null,

    @SerializedName("contacto")
    val contacto: kotlin.String? = null

) {


}

