/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.PiezaRequest

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rentaId 
 * @param deposito 
 * @param cargoPorDanos 
 * @param cargoPorRetraso 
 * @param fechaDevolucionReal 
 * @param piezas 
 */


data class RegistrarDevolucionRequest (

    @SerializedName("rentaId")
    val rentaId: java.util.UUID,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("cargoPorDanos")
    val cargoPorDanos: java.math.BigDecimal? = null,

    @SerializedName("cargoPorRetraso")
    val cargoPorRetraso: java.math.BigDecimal? = null,

    @SerializedName("fechaDevolucionReal")
    val fechaDevolucionReal: java.time.LocalDate? = null,

    @SerializedName("piezas")
    val piezas: kotlin.collections.List<PiezaRequest>? = null

) {


}

