/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.SeleccionSlotDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param empresaId 
 * @param clienteId 
 * @param cantidad 
 * @param selecciones 
 */


data class RentarDisfrazRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null,

    @SerializedName("selecciones")
    val selecciones: kotlin.collections.List<SeleccionSlotDto>? = null

) {


}

