/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rentaId 
 * @param clienteId 
 * @param prendaId 
 * @param fechaDevolucion 
 * @param diasVencida 
 * @param importe 
 * @param deposito 
 */


data class RentaVencidaResponse (

    @SerializedName("rentaId")
    val rentaId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null,

    @SerializedName("diasVencida")
    val diasVencida: kotlin.Long? = null,

    @SerializedName("importe")
    val importe: java.math.BigDecimal? = null,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null

) {


}

