/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaRentaResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param codigoRetiro 
 * @param sucursalId 
 * @param clienteId 
 * @param clienteNombre 
 * @param empleadoId 
 * @param lineas 
 * @param prendaId 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param precioPorDia 
 * @param deposito 
 * @param importe 
 * @param estado 
 */


data class RentaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("clienteNombre")
    val clienteNombre: kotlin.String? = null,

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaRentaResponse>? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null,

    @SerializedName("precioPorDia")
    val precioPorDia: java.math.BigDecimal? = null,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("importe")
    val importe: java.math.BigDecimal? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null

) {


}

