/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.ItemDisfrazDto
import com.costumi.apiclient.models.LineaPrendaRentaDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalId 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param empresaId 
 * @param clienteId 
 * @param items 
 * @param lineas 
 */


data class RentarVariosDisfracesRequest (

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("items")
    val items: kotlin.collections.List<ItemDisfrazDto>? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaPrendaRentaDto>? = null

) {


}

