/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaRentaResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param codigoRetiro 
 * @param sucursalId 
 * @param clienteId 
 * @param clienteNombre 
 * @param empleadoId 
 * @param lineas 
 * @param prendaId 
 * @param fechaRetiro 
 * @param fechaDevolucion 
 * @param precioPorDia 
 * @param deposito 
 * @param importe 
 * @param estado 
 * @param creadaEn 
 * @param entregadaEn 
 * @param devueltaRealEn 
 * @param cerradaEn 
 */


data class RentaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("clienteNombre")
    val clienteNombre: kotlin.String? = null,

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaRentaResponse>? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null,

    @SerializedName("fechaRetiro")
    val fechaRetiro: java.time.LocalDate? = null,

    @SerializedName("fechaDevolucion")
    val fechaDevolucion: java.time.LocalDate? = null,

    @SerializedName("precioPorDia")
    val precioPorDia: java.math.BigDecimal? = null,

    @SerializedName("deposito")
    val deposito: java.math.BigDecimal? = null,

    @SerializedName("importe")
    val importe: java.math.BigDecimal? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("creadaEn")
    val creadaEn: java.time.OffsetDateTime? = null,

    @SerializedName("entregadaEn")
    val entregadaEn: java.time.OffsetDateTime? = null,

    @SerializedName("devueltaRealEn")
    val devueltaRealEn: java.time.OffsetDateTime? = null,

    @SerializedName("cerradaEn")
    val cerradaEn: java.time.OffsetDateTime? = null

) {


}

