/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.HistorialItem

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contenido 
 * @param total 
 * @param pagina 
 * @param tamano 
 * @param totalPaginas 
 */


data class RespuestaPaginadaHistorialItem (

    @SerializedName("contenido")
    val contenido: kotlin.collections.List<HistorialItem>? = null,

    @SerializedName("total")
    val total: kotlin.Long? = null,

    @SerializedName("pagina")
    val pagina: kotlin.Int? = null,

    @SerializedName("tamano")
    val tamano: kotlin.Int? = null,

    @SerializedName("totalPaginas")
    val totalPaginas: kotlin.Int? = null

) {


}

