/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.PrendaResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contenido 
 * @param total 
 * @param pagina 
 * @param tamano 
 * @param totalPaginas 
 */


data class RespuestaPaginadaPrendaResponse (

    @SerializedName("contenido")
    val contenido: kotlin.collections.List<PrendaResponse>? = null,

    @SerializedName("total")
    val total: kotlin.Long? = null,

    @SerializedName("pagina")
    val pagina: kotlin.Int? = null,

    @SerializedName("tamano")
    val tamano: kotlin.Int? = null,

    @SerializedName("totalPaginas")
    val totalPaginas: kotlin.Int? = null

) {


}

