/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param porEntregar 
 * @param activas 
 * @param vencidas 
 * @param cerradas 
 */


data class ResumenDeRentasResponse (

    @SerializedName("porEntregar")
    val porEntregar: kotlin.Long? = null,

    @SerializedName("activas")
    val activas: kotlin.Long? = null,

    @SerializedName("vencidas")
    val vencidas: kotlin.Long? = null,

    @SerializedName("cerradas")
    val cerradas: kotlin.Long? = null

) {


}

