/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalUnidades 
 * @param disponibles 
 * @param danadas 
 * @param enLimpieza 
 * @param perdidas 
 * @param rentadasAhora 
 * @param tasaUtilizacion 
 * @param valorInventario 
 */


data class ResumenInventario (

    @SerializedName("totalUnidades")
    val totalUnidades: kotlin.Long? = null,

    @SerializedName("disponibles")
    val disponibles: kotlin.Long? = null,

    @SerializedName("danadas")
    val danadas: kotlin.Long? = null,

    @SerializedName("enLimpieza")
    val enLimpieza: kotlin.Long? = null,

    @SerializedName("perdidas")
    val perdidas: kotlin.Long? = null,

    @SerializedName("rentadasAhora")
    val rentadasAhora: kotlin.Long? = null,

    @SerializedName("tasaUtilizacion")
    val tasaUtilizacion: java.math.BigDecimal? = null,

    @SerializedName("valorInventario")
    val valorInventario: java.math.BigDecimal? = null

) {


}

