/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param orden 
 * @param prendaId 
 */


data class SeleccionResponse (

    @SerializedName("orden")
    val orden: kotlin.Int? = null,

    @SerializedName("prendaId")
    val prendaId: java.util.UUID? = null

) {


}

