/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoEtiquetaId 
 * @param valorEtiquetaId 
 */


data class SeleccionVarianteDto (

    @SerializedName("tipoEtiquetaId")
    val tipoEtiquetaId: java.util.UUID,

    @SerializedName("valorEtiquetaId")
    val valorEtiquetaId: java.util.UUID

) {


}

