/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.FacetaDto
import com.costumi.apiclient.models.OpcionDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param orden 
 * @param nombre 
 * @param ejePrenda 
 * @param opcional 
 * @param opciones 
 * @param facetas 
 */


data class SlotOpcionesResponse (

    @SerializedName("orden")
    val orden: kotlin.Int? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("ejePrenda")
    val ejePrenda: SlotOpcionesResponse.EjePrenda? = null,

    @SerializedName("opcional")
    val opcional: kotlin.Boolean? = null,

    @SerializedName("opciones")
    val opciones: kotlin.collections.List<OpcionDto>? = null,

    @SerializedName("facetas")
    val facetas: kotlin.collections.List<FacetaDto>? = null

) {

    /**
     * 
     *
     * Values: FIJA,PERSONALIZABLE
     */
    enum class EjePrenda(val value: kotlin.String) {
        @SerializedName(value = "FIJA") FIJA("FIJA"),
        @SerializedName(value = "PERSONALIZABLE") PERSONALIZABLE("PERSONALIZABLE");
    }

}

