/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.PoolDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ejePrenda 
 * @param orden 
 * @param nombre 
 * @param prendaFijaId 
 * @param pool 
 * @param prendasOpcion 
 * @param opcional 
 */


data class SlotDto (

    @SerializedName("ejePrenda")
    val ejePrenda: SlotDto.EjePrenda,

    @SerializedName("orden")
    val orden: kotlin.Int? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("prendaFijaId")
    val prendaFijaId: java.util.UUID? = null,

    @SerializedName("pool")
    val pool: PoolDto? = null,

    @SerializedName("prendasOpcion")
    val prendasOpcion: kotlin.collections.List<java.util.UUID>? = null,

    @SerializedName("opcional")
    val opcional: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: FIJA,PERSONALIZABLE
     */
    enum class EjePrenda(val value: kotlin.String) {
        @SerializedName(value = "FIJA") FIJA("FIJA"),
        @SerializedName(value = "PERSONALIZABLE") PERSONALIZABLE("PERSONALIZABLE");
    }

}

