/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empresaId 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param monto 
 * @param motivo 
 */


data class SolicitarReembolsoDeClienteRequest (

    @SerializedName("empresaId")
    val empresaId: java.util.UUID,

    @SerializedName("tipoConcepto")
    val tipoConcepto: SolicitarReembolsoDeClienteRequest.TipoConcepto,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("motivo")
    val motivo: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

