/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoConcepto 
 * @param conceptoId 
 * @param monto 
 * @param solicitanteClienteId 
 * @param motivo 
 */


data class SolicitarReembolsoRequest (

    @SerializedName("tipoConcepto")
    val tipoConcepto: SolicitarReembolsoRequest.TipoConcepto,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID,

    @SerializedName("monto")
    val monto: java.math.BigDecimal,

    @SerializedName("solicitanteClienteId")
    val solicitanteClienteId: java.util.UUID? = null,

    @SerializedName("motivo")
    val motivo: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }

}

