/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param tipoConcepto 
 * @param conceptoId 
 * @param solicitanteClienteId 
 * @param monto 
 * @param motivoSolicitud 
 * @param estado 
 * @param motivoDecision 
 * @param decididoPorUsuarioId 
 * @param rolDecision 
 * @param creadaEn 
 * @param decididaEn 
 */


data class SolicitudDeReembolsoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("tipoConcepto")
    val tipoConcepto: SolicitudDeReembolsoResponse.TipoConcepto? = null,

    @SerializedName("conceptoId")
    val conceptoId: java.util.UUID? = null,

    @SerializedName("solicitanteClienteId")
    val solicitanteClienteId: java.util.UUID? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null,

    @SerializedName("motivoSolicitud")
    val motivoSolicitud: kotlin.String? = null,

    @SerializedName("estado")
    val estado: SolicitudDeReembolsoResponse.Estado? = null,

    @SerializedName("motivoDecision")
    val motivoDecision: kotlin.String? = null,

    @SerializedName("decididoPorUsuarioId")
    val decididoPorUsuarioId: java.util.UUID? = null,

    @SerializedName("rolDecision")
    val rolDecision: kotlin.String? = null,

    @SerializedName("creadaEn")
    val creadaEn: java.time.OffsetDateTime? = null,

    @SerializedName("decididaEn")
    val decididaEn: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: RENTA,VENTA
     */
    enum class TipoConcepto(val value: kotlin.String) {
        @SerializedName(value = "RENTA") RENTA("RENTA"),
        @SerializedName(value = "VENTA") VENTA("VENTA");
    }
    /**
     * 
     *
     * Values: PENDIENTE,APROBADA,RECHAZADA
     */
    enum class Estado(val value: kotlin.String) {
        @SerializedName(value = "PENDIENTE") PENDIENTE("PENDIENTE"),
        @SerializedName(value = "APROBADA") APROBADA("APROBADA"),
        @SerializedName(value = "RECHAZADA") RECHAZADA("RECHAZADA");
    }

}

