/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param tokenType 
 */


data class TokenResponse (

    @SerializedName("accessToken")
    val accessToken: kotlin.String? = null,

    @SerializedName("refreshToken")
    val refreshToken: kotlin.String? = null,

    @SerializedName("tokenType")
    val tokenType: kotlin.String? = null

) {


}

