/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sucursalDestinoId 
 * @param cantidad 
 */


data class TransferirStockRequest (

    @SerializedName("sucursalDestinoId")
    val sucursalDestinoId: java.util.UUID,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null

) {


}

