/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.MovimientoResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param sucursalId 
 * @param empleadoId 
 * @param fondoInicial 
 * @param estado 
 * @param efectivoContado 
 * @param corte 
 * @param diferenciaEfectivo 
 * @param movimientos 
 * @param abiertoEn 
 * @param cerradoEn 
 */


data class TurnoResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("fondoInicial")
    val fondoInicial: java.math.BigDecimal? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("efectivoContado")
    val efectivoContado: java.math.BigDecimal? = null,

    @SerializedName("corte")
    val corte: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,

    @SerializedName("diferenciaEfectivo")
    val diferenciaEfectivo: java.math.BigDecimal? = null,

    @SerializedName("movimientos")
    val movimientos: kotlin.collections.List<MovimientoResponse>? = null,

    @SerializedName("abiertoEn")
    val abiertoEn: java.time.OffsetDateTime? = null,

    @SerializedName("cerradoEn")
    val cerradoEn: java.time.OffsetDateTime? = null

) {


}

