/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param email 
 * @param rol 
 * @param empresaId 
 */


data class UsuarioActualResponse (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("rol")
    val rol: kotlin.String? = null,

    @SerializedName("empresaId")
    val empresaId: kotlin.String? = null

) {


}

