/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param empresaId 
 * @param tipoEtiquetaId 
 * @param valor 
 * @param archivada 
 */


data class ValorEtiquetaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("empresaId")
    val empresaId: java.util.UUID? = null,

    @SerializedName("tipoEtiquetaId")
    val tipoEtiquetaId: java.util.UUID? = null,

    @SerializedName("valor")
    val valor: kotlin.String? = null,

    @SerializedName("archivada")
    val archivada: kotlin.Boolean? = null

) {


}

