/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param valorEtiquetaId 
 * @param valorNombre 
 * @param cantidad 
 */


data class ValorDeFacetaDto (

    @SerializedName("valorEtiquetaId")
    val valorEtiquetaId: java.util.UUID? = null,

    @SerializedName("valorNombre")
    val valorNombre: kotlin.String? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Int? = null

) {


}

