/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param valor 
 * @param unidades 
 * @param monto 
 */


data class ValorEtiquetaRanking (

    @SerializedName("valor")
    val valor: kotlin.String? = null,

    @SerializedName("unidades")
    val unidades: kotlin.Long? = null,

    @SerializedName("monto")
    val monto: java.math.BigDecimal? = null

) {


}

