/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.costumi.apiclient.models

import com.costumi.apiclient.models.LineaResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param codigoRetiro 
 * @param sucursalId 
 * @param empleadoId 
 * @param clienteId 
 * @param clienteNombre 
 * @param descuento 
 * @param total 
 * @param estado 
 * @param montoReembolsado 
 * @param lineas 
 * @param creadaEn 
 */


data class VentaResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("codigoRetiro")
    val codigoRetiro: kotlin.String? = null,

    @SerializedName("sucursalId")
    val sucursalId: java.util.UUID? = null,

    @SerializedName("empleadoId")
    val empleadoId: java.util.UUID? = null,

    @SerializedName("clienteId")
    val clienteId: java.util.UUID? = null,

    @SerializedName("clienteNombre")
    val clienteNombre: kotlin.String? = null,

    @SerializedName("descuento")
    val descuento: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null,

    @SerializedName("estado")
    val estado: kotlin.String? = null,

    @SerializedName("montoReembolsado")
    val montoReembolsado: java.math.BigDecimal? = null,

    @SerializedName("lineas")
    val lineas: kotlin.collections.List<LineaResponse>? = null,

    @SerializedName("creadaEn")
    val creadaEn: java.time.OffsetDateTime? = null

) {


}

