/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.costumi.apiclient.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param intentoId 
 * @param idPagoExterno 
 */


data class WebhookPagoRequest (

    @SerializedName("intentoId")
    val intentoId: java.util.UUID,

    @SerializedName("idPagoExterno")
    val idPagoExterno: kotlin.String? = null

) {


}

